name: build artifact

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./helloworld

    - name: Run tests
      run: |
        mvn -B package --file pom.xml
        mkdir artifacts && cp target/*.jar artifacts
        cd artifacts && ls
      working-directory: ./helloworld

    - name: save artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: artifacts
