name: build artifact

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./helloworld

    - name: upload Artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{github.workspace}}/target/*.jar'
