name: CI/CD Pipeline

on: [push]
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # or 'adopt', 'zulu', etc.
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./helloworld/pom.xml

    - name: Run tests
      run: mvn test
      working-directory: ./helloworld/pom.xml

    - name: Package application
      run: mvn package
      working-directory: ./helloworld/pom.xml

    - name: Deploy to AWS EC2
      if: github.ref == 'refs/heads/master'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          mkdir -p ~/app
          rm -rf ~/app/*
        EOF
        scp target/helloworld-0.0.1-SNAPSHOT.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/app/
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ~/app
          nohup java -jar helloworld-0.0.1-SNAPSHOT.jar &
        EOF
